##############
# Commitlint #
##############
# [OVERVIEW] Lint commit messages for compliance with the Conventional Commits specification:
# https://commitlint.js.org
#
# [INFO] Conventional Commits description:
# https://conventionalcommits.org
#
# [RULES]
# https://commitlint.js.org/#/reference-rules
#
# [INFO] Default rules preset, installed by “npm install --save-dev @commitlint/config-conventional”:
# https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js
#
#
# [INFO] Probot Commitlint check commits in GitHub pull requests:
# https://commitlint-probot.wizardtales.com/probot
# https://github.com/z0al/commitlint-bot
#
# [NOTE] Probot Commitlint doesn’t work with commitlint configuration files:
# https://github.com/ahmed-taj/commitlint-bot/pull/8
# https://probot.github.io/apps/commitlint/
#
# [INFO] commitlint rules:
# 0 — disable, 1 — warning, 2 — error:
# I’m not use warnings, that CI exit if any warning.
# https://github.com/marionebl/commitlint/blob/master/docs/reference-rules.md#rules
# https://github.com/SuperPaintman/commitlint-config-pedantic/blob/master/configs/base.yml
rules:

  # [NOTE] “body” is the long commit description, which may contain long URL’s. I think it makes sense to set it to a high value.
  body-max-length:
  - 2
  - always
  - 250

  # [NOTE] 120 as in Python
  footer-max-length:
  - 2
  - always
  - 120

  # [NOTE] 120 as in Python
  header-max-length:
  - 2
  - always
  - 120

  # [NOTE] I set that subject may be written in any case, because many words and objects in programming,
  # with which I begin my subjects, begin with a small letter
  subject-case:
  - 0
  - always

  # [NOTE] I added personal types for my projects.
  # I think this will help provide more accurate information about the type of changes made.
  type-enum:
  - 2
  - always
  -

    # [INFO] Default types

    # A new feature
    - feat

    # A bug fix
    - fix

    # Documentation only changes
    - docs

    # Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    # Validation changes — this type.
    - style

    # A code change that neither fixes a bug nor adds a feature
    - refactor

    # A code change that improves performance
    - perf

    # Adding missing or correcting existing tests
    - test

    # Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
    - ci

    # [INFO] Tool changes, configuration changes,
    # and changes to things that do not actually go into production at all:
    # https://stackoverflow.com/a/26944812/5951529
    - chore

    # Building tools changes (example scopes: grunt, gulp)
    - build

    # Reverts a previous commit
    - revert


    # [INFO] Personal types

    # VCS changes (example scopes: bazaar, mercurial, git)
    - vcs

    # Debugging.
    - debug

    # [INFO] Update
    - upd

    # [INFO] Changes for linters/checkers/validators.
    # Example scopes — “eslint”, “stylint”
    - lint

    # [INFO] Migrate from one tool to another
    - migrate

    # [INFO] Delete unneeded
    - del


  # [INFO] Sign-off commits:
  # https://stackoverflow.com/a/14044024/5951529
  #
  # I’m not use it in my projects:
  # 1. gpg-sign more really certify commit author,
  # 2. unobfuscate e-mail push to GitHub,
  # 3. User needs add “Signed-off-by: Your Name <your.email@example.com>” each time,
  # it may take a lot of time.
  signed-off-by:
  - 2
  - always
  - "Signed-off-by:"
