build_script:
- grunt shell:commitlint

cache:
- "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

install:
- npm install -g grunt-cli
- npm ci --loglevel=error

platform: x64
