platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:

  PYTHON: C:\Python312-x64

install:
- npm install -g grunt-cli
- npm install
- npx simple-git-hooks

build_script:
- git log -1
- git log -1 --pretty=format:"%s%n%n%b"
- git log -1 --pretty=format:"%s%n%b"
- grunt shell:commitlint --debug --stack --verbose
