platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:

  PYTHON: C:\Python312-x64

install:
- npm install -g grunt-cli
- npm install

build_script:
- grunt shell:commitlint --debug --stack --verbose
