platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:

  API_KEY_APPVEYOR:

    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

  PYTHON: C:\Python312-x64

install:
- choco install nodejs
- npm install -g grunt-cli
- pip install djlint

build_script:
- grunt shell:djlint
