version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
    - checkout
    - run: nvm use 18.6.0
    - run: node --version
    - run: npm install -g grunt-cli
    - run: npm install
    - run: grunt closure-compiler --verbose --stack
