version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
    - checkout
    - run: nvm install node --reinstall-packages-from=node
    - run: npm install -g grunt-cli
    - run: npm install
    - run: grunt closure-compiler --verbose --stack
